### ISSUE TITLE
EOL notice for python33

### ISSUE THREAD

**Issue by b-harper** [iuscommunity/announce#7]
The expected end-of-life (EOL) date for Python 3.3 is [2017-09-29][0], two months from now.  Once Python 3.3 goes EOL, all python33 packages will be moved into the archive repositories and will received no more updates or support.  

[0]: https://www.python.org/dev/peps/pep-0398/#x-end-of-life

**Comment by b-harper** [comment]
Just a reminder, Python 3.3 is expected to go EOL in one month.

**Comment by b-harper** [comment]
We are just under two weeks from the expected EOL date for Python 3.3.

**Comment by b-harper** [comment]
Last week, [the expected final release of Python 3.3 was released][0].  Packages have been in the testing repositories for just under one week.  Seeing that this is a security, we will be moving them to the stable repositories during tonight's automation run.  They will remain in the stable repositories for two weeks.  Then will we EOL all python33 packages and move them into the archive repositories. 



[0]: https://www.python.org/downloads/release/python-337/

**Comment by carlwgeorge** [comment]
All python33 packages have been moved to the archive repositories.
