### ISSUE TITLE
Announcements of releases with security fixes

### ISSUE THREAD

**Issue by wojciech-kopras** [iuscommunity/announce#9]
Hi,
How can I get notified that in IUS repo was released a package with security fixes? E.g. for CentOS I get it from this list https://lists.centos.org/pipermail/centos-announce/ .

**Comment by carlwgeorge** [comment]
Every IUS package has a corresponding repo in the [iuscommunity-pkg](https://github.com/iuscommunity-pkg) organization.  Subscribing to those repos for the specific packages your are interested in will provide you with notifications when new releases are tagged.  However, we don't make any distinction between releases on the basis of security.  If you only want security fixes, I recommend stock RHEL/CentOS packages.  IUS packages are designed to follow the upstream releases, which routinely contain new features, bug fixes, and security fixes in the same release.  Categorizing IUS packages releases into these categories is not tenable.
